### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

### ISSUE THREAD

**Issue by dELUSION-MS** [googleworkspace/PyDrive#214]
I was trying to upload a file in shared drive and this error has occurred now I can't solve it!

Using 
```
PyDrive Version: 1.3.1
OS : Ubuntu 18.04 LTS (AWS Cloud9)
```

```
2020-12-16 03:56:33,217 - googleapiclient.discovery_cache - WARNING - file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2020-12-16 03:56:35,201 - root - ERROR - Downloading Exception occured
Traceback (most recent call last):
  File "main.py", line 83, in download
    file_to_upload.Upload(param={'supportsTeamDrives': True, 'http': http})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pydrive/files.py", line 285, in Upload
    self._FilesInsert(param=param)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pydrive/files.py", line 369, in _FilesInsert
    http=self.http)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 879, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/googleapiclient/http.py", line 1058, in next_chunk
    self.resumable_uri, method="PUT", body=data, headers=headers
  File "/home/ubuntu/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/httplib2/__init__.py", line 1690, in _request
    content,
httplib2.RedirectMissingLocation: Redirected but the response is missing a Location: header.
```

**Comment by shcheklein** [comment]
Could you try the PyDrive2 lib instead?

**Comment by dELUSION-MS** [comment]
Thankyou! It took a lot to change my code, **But it worked!**
Thanks a lot.😊😊😊😊
